export const TAB_LIST = {
  HOME: "HOME",
  ARTIST: "ARTIST",
  ALBUM: "ALBUM",
  PODCAST: "PODCAST",
  RECENT: "RECENT",
  FAVOURITE: "FAVOURITE",
  PLAYLIST: "PLAYLIST",
  SETTINGS: "SETTINGS",
  ACCOUNT: "ACCOUNT",
};
